// @flow

export const UPLOADER_EVENTS = {
	BATCH_ADD: "BATCH-ADD",
	BATCH_START: "BATCH-START",
	BATCH_FINISH: "BATCH-FINISH",
	BATCH_ABORT: "BATCH-ABORT",
	BATCH_CANCEL: "BATCH-CANCEL",

	FILE_START: "FILE-START",
	FILE_CANCEL: "FILE-CANCEL",
	FILE_PROGRESS: "FILE-PROGRESS",
	FILE_FINISH: "FILE-FINISH",
	FILE_ABORT: "FILE-ABORT",
	FILE_ERROR: "FILE-ERROR",
};

export const PROGRESS_DELAY = 100;