name: Bundle Size Report
description: report (summary & PR) bundle size with comparison to master

inputs:
    reportData:
        description: 'The report data to process'
        required: true

runs:
    using: composite
    steps:
        -   name: Process Report
            id: bundle-size-report
            uses: actions/github-script@v7
            env:
                BUNDLE_SIZE_REPORT: ${{ inputs.reportData }}
            with:
                script: |
                    const { default: script } = await import('${{ github.workspace }}/.github/actions/bundle-size-report/index.mjs');
                    return await script({ fetch, github, context, core });

        -   name: Commit Master Bundle Size Report
            id: commit-report
            if: ${{ steps.bundle-size-report.outputs.SAVED_MASTER_REPORT }}
            shell: bash
            run: |
                git config user.email "ci@react-uploady.org"
                git config user.name "Uploady CI"
                git status
                git commit -a -m "chore: update master bundle size report"
                echo "committed=true" >> $GITHUB_OUTPUT

        -   name: check committed output
            shell: bash
            run: |
                echo "Did Commit? ${{ steps.commit-report.outputs.committed }}"

        -   name: Create PR for Master Bundle Size Report
            if: ${{ steps.commit-report.outputs.committed == 'true' }}
            uses: peter-evans/create-pull-request@v6
            with:
                title: "chore: update master bundle size report"
                body: "Automatic PR for new bundle size report"
                branch: updated-bundle-size-report-${{ github.run_id }}
                base: "master"
                commit-message: "chore: commit new master bundle size report"

        -   name: Add Bundle Size Report as PR Comment (for PR Builds)
            uses: mshick/add-pr-comment@v2
            with:
                message: |
                    ## 📦 Bundle Size Report
                    ${{ steps.bundle-size-report.outputs.BUNDLE_SIZE_REPORT_TABLE }}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
