name: "Prepare Node Env"
description: "start node env with pnpm"

inputs:
    dir:
        description: working directory
        default: "."
        required: false
    with-cypress:
        description: whether to cache cypress bin folder
        required: false
    with-frozen:
        description: whether to use --frozen--lockfile
        required: false
        default: "true"

runs:
    using: composite
    steps:
        -   uses: pnpm/action-setup@v4
            with:
                version: 8
                run_install: false

        -   uses: actions/setup-node@v4
            with:
                node-version: "20.15.1"
                cache: "pnpm"
                cache-dependency-path: "${{ inputs.dir }}/pnpm-lock.yaml"
                node-version-file: "${{ inputs.dir }}/.nvmrc"

        -   name: Install deps
            shell: bash
            run: pnpm install ${{ inputs.with-frozen == 'true' && '--frozen-lockfile' || '' }}
            working-directory: ${{ inputs.dir }}

        -   name: Set up Cypress binary cache
            if: ${{ inputs.with-cypress == 'true' }}
            uses: actions/cache@v4
            with:
                path: ~/.cache/Cypress
                key: ${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}
