name: "Prepare Node Env"
description: "start node env with pnpm"

runs:
    using: composite
    steps:
        -   uses: pnpm/action-setup@v4
            with:
                version: 8
                run_install: false

        -   uses: actions/setup-node@v3
            with:
                node-version: "20.15.1"
                cache: "pnpm"

        -   name: Install deps
            shell: bash
            run: pnpm install --frozen-lockfile
